version: "3.7"

services:
  app-server:
    image: "nginx:1.18"
    container_name: "teratail-app-server"
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./app:/usr/share/nginx/html"
    networks:
      app-network:

  php-fpm:
    image: "php-fpm:teratail"
    build:
      context: "./"
      dockerfile: "Dockerfile.php-fpm"
    container_name: "teratail-php-fpm"
    volumes:
      - "./app:/var/www/html"
    networks:
      app-network:

networks:
  app-network:
    name: "teratail-app-network"

